#!/bin/bash -e

# default environment variables
HTTP_PORT=${HTTP_PORT:-8080}
CLIENT_PORT=${CLIENT_PORT:-2181}
CONNECT_PORT=${CONNECT_PORT:-2888}
ELECTION_PORT=${ELECTION_PORT:-3888}

if [[ -n ${S3_BUCKET} ]]; then
    CONFIG="-c s3 --s3credentials /opt/s3-credentials.properties --s3config ${S3_BUCKET}:${S3_PREFIX} --s3region ${AWS_REGION}"
else
    CONFIG="-c file"
fi

cat <<EOF > /exhibitor/exhibitor.properties
zookeeper-install-directory=/zookeeper
client-port=$CLIENT_PORT
connect-port=$CONNECT_PORT
election-port=$ELECTION_PORT
zoo-cfg-extra=tickTime\=2000&initLimit\=10&syncLimit\=5&quorumListenOnAllIPs\=true
auto-manage-instances-settling-period-ms=0
auto-manage-instances=1
zookeeper-data-directory=/zookeeper/snapshots
zookeeper-log-directory=/zookeeper/transactions
log-index-directory=/zookeeper/transactions
java-environment=export JAVA_OPTS\="$JAVA_OPTS"
EOF

cat <<EOF > /zookeeper/conf/java.env
ZOO_LOG_DIR="/var/log/zookeeper"
EOF

cat <<EOF > /opt/s3-credentials.properties
com.netflix.exhibitor.s3.access-key-id=${AWS_ACCESS_KEY}
com.netflix.exhibitor.s3.access-secret-key=${AWS_SECRET_KEY}
EOF

java -jar /exhibitor/exhibitor-1.5.6.jar \
    ${CONFIG} \
    --defaultconfig=/exhibitor/exhibitor.properties \
    --port=${HTTP_PORT} \
    --hostname ${HOSTNAME} \
    $@
